-- Table: public.tr_wecare

-- DROP TABLE IF EXISTS public.tr_wecare;

CREATE TABLE IF NOT EXISTS public.tr_wecare
(
    intid SERIAL NOT NULL ,
    numkssmpensionerid integer UNIQUE NOT NULL,
    numkssmefileid numeric,
    scheme_id integer,
    district integer,
    application_no numeric,
    reg_no numeric,
    application_date date,
    applicant_age integer,
    applicant_dob date,
    applicant_genderid integer,
    memberbpl integer,
    rationcard_no character varying(50) COLLATE pg_catalog."default",
    bplcertificate_no character varying(15) COLLATE pg_catalog."default",
    bplcertificate_date date,
    applicant_bankaccountno character varying(50) COLLATE pg_catalog."default",
    applicant_bank integer,
    applicant_bank_branch integer,
    applicant_ifsccode character varying(50) COLLATE pg_catalog."default",
    applicant_aadharno numeric,
    file_status integer,
    sourceid integer,
    user_id integer,
    icdsofficer_id integer,
    fieldenquiry_date date,
    icdsremarks character varying(1000) COLLATE pg_catalog."default",
    icdseligibility_id integer,
    cdporec_date date,
    cdpoeligibility_id integer,
    remarks character varying(1000) COLLATE pg_catalog."default",
    cdposubmit_date date,
    dtdecision_date timestamp without time zone,
    chvreason character varying(1000) COLLATE pg_catalog."default",
    penstart_date date,
    verifier_id integer,
    verifier_date date,
    verifierremarks character varying(1000) COLLATE pg_catalog."default",
    approver_id integer,
    approver_date date,
    approverremarks character varying(1000) COLLATE pg_catalog."default",
    category_id integer,
    CONSTRAINT pk_constraint_name PRIMARY KEY (intid)
)